kind: pipeline
type: docker
name: Swift-ALLIN

trigger:
    event:
        - push

steps:
  - name: build
    image: swift:latest
    commands:
        - cd Sources/allin/allin
        - swift build

  - name: test
    image: swift:latest
    commands:
        - cd Sources/allin/allinTests 
        - swift test
    depends_on: [build]
