kind: pipeline
type: docker
name: Swift-ALLIN

trigger:
    event:
        - push

steps:
  - name: build
    image: swift:latest
    commands:
        - cd Sources/Model
        - swift build

  - name: build
    image: swift:latest
    commands:
        - cd Sources/Model
        - swift test
